# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb74b4c3035bd1e260d6020bcbcd54159d6c3dbae7ca85e472a6e4a7c808173b1bbd9a8ffda466fd582b84700ebc7c0fd6ef0c60068933023fc8c05aec4cbcdb

test:
  secret_key_base: 8cc712ec4a6ba3e367c94625f159fab5969e6b513326b409d6d3f363d37176f5b5ae6a07fb8900654f19b5555e78d2468c47f299fe736ea65c19d729381809b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
